export const CARREERS = [
  'Heavy and Tractor-Trailer Truck Driver',
  'Registered Nurse',
  'First-Line Supervisors of Retail Sales Worker',
  'Retail Salesperson',
  'Software Developers, Application',
  'Customer Service Representative',
  'Marketing Manager',
  'First-Line Supervisors of Food Preparation and Serving Worker',
  'First-Line Supervisors of Office and Administrative Support Worker',
  'Computer User Support Specialist',
  'Computer Systems Analyst',
  'Network and Computer Systems Administrator',
  'Web Developer',
  'Management Analyst',
  'Medical and Health Services Manager',
  'Accountant',
  'Information Technology Project Manager',
  'Sales Manager',
  'Industrial Engineer',
  'Executive Secretaries and Executive Administrative Assistant',
  'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Product',
  'Maintenance and Repair Workers, General',
  'Social and Human Service Assistant',
  'Entrepreneurs Wanted – Business Opportunitie',
  'First-Line Supervisors of Production and Operating Worker',
  'Nursing Assistant',
  'Combined Food Preparation and Serving Workers, Including Fast Food',
  'Licensed Practical and Licensed Vocational Nurse',
  'General and Operations Manager',
  'Bookkeeping, Accounting, and Auditing Clerk',
  'Managers, All Other',
  'Financial Managers, Branch or Department',
  'Insurance Sales Agent',
  'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Product',
  'Sales Representatives, Services, All Other',
  'Sales Agents, Financial Service',
  'Critical Care Nurse',
  'Cashier',
  'Computer Systems Engineers/Architect',
  'Market Research Analysts and Marketing Specialist',
  'Physical Therapist',
  'Medical Assistant',
  'First-Line Supervisors of Non-Retail Sales Worker',
  'Software Quality Assurance Engineers and Tester',
  'First-Line Supervisors of Mechanics, Installers, and Repairer',
  'Information Security Analyst',
  'Medical Secretarie',
  'Laborers and Freight, Stock, and Material Movers, Hand',
  'Security Guard',
  'Family and General Practitioner',
];

export const GENDERS = [
  "Male",
  "Female",
  "Non-binary",
  'Other',
];
